# Generated by Django 3.2.7 on 2021-09-25 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.TextField()),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('quantity', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_available', models.BooleanField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
